# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('places_limit', models.PositiveIntegerField()),
                ('advertising', models.BooleanField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='app.Country')),
            ],
        ),
    ]
