# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=30)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('capacity', models.IntegerField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='app.City')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='app.Partner')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='app.PlaceType')),
            ],
        ),
    ]
